// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEWixua9suWCmG8MeGsRMIi8QpULPc8o',
    appId: '1:942542689277:android:c41114696938326aff7f94',
    messagingSenderId: '942542689277',
    projectId: 'nottes-muneeb',
    storageBucket: 'nottes-muneeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQeePNHXcC4X6xtw-Ez9nVzQsXc1IVoY',
    appId: '1:942542689277:ios:ddbbd26cc31c8f07ff7f94',
    messagingSenderId: '942542689277',
    projectId: 'nottes-muneeb',
    storageBucket: 'nottes-muneeb.appspot.com',
    iosClientId: '942542689277-58kkundvrsof0ka6mph90ukta7ciimjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
